In [3]:
import numpy as np
import scipy.ndimage as ndimage 

x, y = (63*np.random.random((2, 8))).astype(np.int)
print x,y

[31 17 59 39 60 57 23 52] [41  9 59 42 21 23  4 53]


In [6]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:

ndimage.correlate1d(a, [1, 2, 3])   #the [1,2,3] are kernel weights

array([[ 3,  8, 14, 17],
       [27, 32, 38, 41],
       [51, 56, 62, 65]])

In [10]:
def fnc(iline, oline):
     oline[...] = iline[:-2] + 2 * iline[1:-1] + 3 * iline[2:]
ndimage.generic_filter1d(a, fnc, 3)

array([[ 3,  8, 14, 17],
       [27, 32, 38, 41],
       [51, 56, 62, 65]])

In [12]:
def fnc(iline, oline):
    print "in",iline
    oline[...] = iline[:-2] + 2 * iline[1:-1] + 3 * iline[2:]
    print "out",oline
ndimage.generic_filter1d(a, fnc, 3)

in [ 0.  0.  1.  2.  3.  3.]
out [  3.   8.  14.  17.]
in [ 4.  4.  5.  6.  7.  7.]
out [ 27.  32.  38.  41.]
in [  8.   8.   9.  10.  11.  11.]
out [ 51.  56.  62.  65.]


array([[ 3,  8, 14, 17],
       [27, 32, 38, 41],
       [51, 56, 62, 65]])